language: node_js
node_js:
  - "5.3.0"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before script:
  - npm install -g gulp
script:
  - npm run configure
  - gulp build

